version: 2
jobs:
  build:
    docker:
      - image: ubuntu:14.04

    steps:
      - checkout

      # Deploy commands
      - deploy:
          name: Sample test to reach aws
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              pip install awscli --upgrade --user
              echo 'Pujitha Deploying develop'
              deploy.sh
            else
              echo "Not master branch. So not deploying"
            fi
