version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76

      # Deploy commands
      - deploy:
          name: Sample test to reach aws
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              pip install awscli --upgrade --user
              echo 'Pujitha Deploying develop'
              deploy.sh
            else
              echo "Not master branch. So not deploying"
            fi
